<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="css/bootstrap-theme.css" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
    <link href="css/my-style.css" rel="stylesheet">

    <title>JDM</title>
</head>

<body role="document">
<div class="container">
   
        <div id="menu" class=""><!-- col-xs-6 col-sm-3 col-md-2 -->
           <nav>

           <img src="images/jdm-logo.png" height="80px" style="margin: 10px 0; margin-right: 20px;">
            
                <!-- <ul class="nav">
                    <li><a href="index.php">Home</a></li>
                    <li><a href="page1.php">Page1</a></li>
                    <li><a href="studentISv1.php">StudentV1</a></li>
                    <li><a href="studentISv2.php">StudentV1</a></li>
                </ul> -->
                <ul id="nav-links">
                    <li><a href="index.html" class="active">Home</a></li>
                    <li><a href="about_me.html">Used Cars</a></li>
                    <li><a href="projects.html">New Cars</a></li>
                    <li><a href="contact_me.html">Japan's Finest</a></li>
                    <li style="margin-left: auto;"><a style=" text-align: center;" href="https://github.com/HasanMullerKhan">
                                            <i class="far fa-user"></i><br>Sign In</a></li>
                </ul>
            </nav>
        </div>

    </div>

    <div class="jumbotron">
        <img src="images/mx5.jpg" style="width: 100%;">

    </div>

    <div id="content" class="col-xs-6 col-sm-9 col-md-10">

